name: build
on:
    push:
        tags:
            - 'v*'
jobs:
    build:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: install # will run `yarn install` command
            - uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: build  &&  tar -jvzf dist.tar.gz dist # will run `yarn build` command

            - uses: 'marvinpinto/action-automatic-releases@latest'
              with:
                  repo_token: '${{ secrets.GITHUB_TOKEN }}'
                  automatic_release_tag: 'latest'
                  prerelease: true
                  title: 'Development Build'
                  files: |
                      dist.tar.gz
